// Self-contained MIRAGE golden fixture dumper.
//
// This mirrors the local C++ reference implementation closely enough for small
// deterministic parity fixtures:
// - faiss/impl/MIRAGE.cpp: gen_random, init_graph, update, add_reverse_edges
// - faiss/impl/HNSW.cpp: random_level / prepare_level_tab_mirage
// - faiss/utils/random.cpp: RandomGenerator over std::mt19937
//
// Important: the Layer-0 injected graph emitted by this self-contained tool is
// diagnostic. The authoritative injected graph should be generated by
// dump_mirage_authoritative.cpp, which calls the real
// IndexHNSW::init_level_0_from_knngraph implementation and dumps
// hierarchy.hnsw.neighbors.

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <iomanip>
#include <iostream>
#include <map>
#include <queue>
#include <random>
#include <set>
#include <string>
#include <unordered_set>
#include <vector>

namespace {

constexpr int kN = 64;
constexpr int kDim = 8;
constexpr int kS = 16;
constexpr int kR = 4;
constexpr int kIter = 15;
constexpr int kNumReverseEdges = 96;
constexpr int kMirageSeed = 2021;
constexpr int kHnswM = 16;
constexpr int kHnswM0 = 2 * kHnswM;
constexpr int kLayer0K = kS;
constexpr int kHnswLevelSeed = 12345;
constexpr int kShuffleSeed = 789;

struct Neighbor {
    int id = 0;
    float distance = 0.0f;
    bool flag = false;

    Neighbor() = default;

    Neighbor(int id, float distance, bool flag)
        : id(id), distance(distance), flag(flag) {}

    bool operator<(const Neighbor& other) const {
        return distance < other.distance;
    }
};

struct NodeDistFarther {
    float distance = 0.0f;
    int id = 0;

    NodeDistFarther(float distance, int id) : distance(distance), id(id) {}

    bool operator<(const NodeDistFarther& other) const {
        return distance > other.distance;
    }
};

struct Layer0Stats {
    int total_edges = 0;
    int min_degree = 0;
    int max_degree = 0;
    double avg_degree = 0.0;
    std::map<int, int> degree_histogram;
    int reciprocal_edges = 0;
    double reciprocity_ratio = 0.0;
    int weak_connected_components = 0;
    int largest_weak_component = 0;
};

class RandomGenerator {
public:
    explicit RandomGenerator(int64_t seed) : mt_(static_cast<unsigned int>(seed)) {}

    int rand_int(int max) {
        return static_cast<int>(mt_() % static_cast<uint32_t>(max));
    }

    float rand_float() {
        return mt_() / static_cast<float>(mt_.max());
    }

private:
    std::mt19937 mt_;
};

float vector_value(int i, int dim) {
    const int raw = ((i + 1) * 37 + (dim + 3) * 17 + (i * dim) * 13) % 1009;
    return (static_cast<float>(raw) - 504.0f) / 100.0f;
}

std::vector<std::vector<float>> generate_vectors() {
    std::vector<std::vector<float>> vectors(kN, std::vector<float>(kDim));
    for (int i = 0; i < kN; ++i) {
        for (int d = 0; d < kDim; ++d) {
            vectors[i][d] = vector_value(i, d);
        }
    }
    return vectors;
}

float l2_distance(const std::vector<std::vector<float>>& vectors, int a, int b) {
    float sum = 0.0f;
    for (int d = 0; d < kDim; ++d) {
        const float diff = vectors[a][d] - vectors[b][d];
        sum += diff * diff;
    }
    return sum;
}

void gen_random(std::mt19937& rng, int* addr, int size, int n) {
    for (int i = 0; i < size; ++i) {
        addr[i] = static_cast<int>(rng() % static_cast<uint32_t>(n - size));
    }
    std::sort(addr, addr + size);
    for (int i = 1; i < size; ++i) {
        if (addr[i] <= addr[i - 1]) {
            addr[i] = addr[i - 1] + 1;
        }
    }
    const int off = static_cast<int>(rng() % static_cast<uint32_t>(n));
    for (int i = 0; i < size; ++i) {
        addr[i] = (addr[i] + off) % n;
    }
}

class MirageReference {
public:
    explicit MirageReference(const std::vector<std::vector<float>>& vectors)
        : vectors_(vectors), graph_(kN) {}

    void build() {
        init_graph();

        for (int r = 0; r < kR; ++r) {
            for (int it = 0; it < kIter; ++it) {
                update();
            }
            if (r != kR - 1) {
                add_reverse_edges();
            }
        }

        layer0_.resize(kN);
        for (int u = 0; u < kN; ++u) {
            auto& pool = graph_[u];
            std::sort(pool.begin(), pool.end());
            pool.erase(
                std::unique(
                    pool.begin(),
                    pool.end(),
                    [](const Neighbor& a, const Neighbor& b) {
                        return a.id == b.id;
                    }),
                pool.end());

            layer0_[u].reserve(pool.size());
            for (const Neighbor& nn : pool) {
                layer0_[u].push_back(nn.id);
            }
        }
    }

    const std::vector<std::vector<int>>& layer0() const {
        return layer0_;
    }

private:
    void init_graph() {
        std::mt19937 rng(kMirageSeed * 7741);
        for (int i = 0; i < kN; ++i) {
            std::vector<int> tmp(kS);
            gen_random(rng, tmp.data(), kS, kN);

            for (int j = 0; j < kS; ++j) {
                const int id = tmp[j];
                if (id == i) {
                    continue;
                }
                graph_[i].emplace_back(id, l2_distance(vectors_, i, id), true);
            }
            std::make_heap(graph_[i].begin(), graph_[i].end());
            graph_[i].reserve(8);
        }
    }

    void insert_nn(int id, int nn_id, float distance, bool flag) {
        graph_[id].emplace_back(nn_id, distance, flag);
    }

    void update() {
        for (int u = 0; u < kN; ++u) {
            std::vector<Neighbor> old_pool;
            old_pool.swap(graph_[u]);

            std::sort(old_pool.begin(), old_pool.end());
            old_pool.erase(
                std::unique(
                    old_pool.begin(),
                    old_pool.end(),
                    [](const Neighbor& a, const Neighbor& b) {
                        return a.id == b.id;
                    }),
                old_pool.end());

            std::vector<Neighbor> new_pool;
            new_pool.reserve(old_pool.size());
            std::unordered_set<int> new_ids;

            for (const Neighbor& nn : old_pool) {
                if (new_ids.find(nn.id) != new_ids.end()) {
                    continue;
                }

                bool ok = true;
                for (const Neighbor& other_nn : new_pool) {
                    if (!nn.flag && !other_nn.flag) {
                        continue;
                    }

                    const float distance = l2_distance(vectors_, nn.id, other_nn.id);
                    if (distance < nn.distance) {
                        ok = false;
                        insert_nn(other_nn.id, nn.id, distance, true);
                        break;
                    }
                }

                if (ok) {
                    new_pool.push_back(nn);
                    new_ids.insert(nn.id);
                }
            }

            for (Neighbor& nn : new_pool) {
                nn.flag = false;
            }
            graph_[u] = std::move(new_pool);
        }
    }

    void add_reverse_edges() {
        std::vector<std::vector<Neighbor>> reverse_pools(kN);

        for (int u = 0; u < kN; ++u) {
            for (const Neighbor& nn : graph_[u]) {
                reverse_pools[nn.id].emplace_back(u, nn.distance, nn.flag);
            }
        }

        for (int u = 0; u < kN; ++u) {
            auto& pool = graph_[u];
            for (Neighbor& nn : pool) {
                nn.flag = true;
            }
            auto& rpool = reverse_pools[u];
            rpool.insert(rpool.end(), pool.begin(), pool.end());
            pool.clear();
            std::sort(rpool.begin(), rpool.end());
            rpool.erase(
                std::unique(
                    rpool.begin(),
                    rpool.end(),
                    [](const Neighbor& a, const Neighbor& b) {
                        return a.id == b.id;
                    }),
                rpool.end());
            if (static_cast<int>(rpool.size()) > kNumReverseEdges) {
                rpool.resize(kNumReverseEdges);
            }
        }

        for (int u = 0; u < kN; ++u) {
            for (const Neighbor& nn : reverse_pools[u]) {
                graph_[nn.id].emplace_back(u, nn.distance, nn.flag);
            }
        }

        for (int u = 0; u < kN; ++u) {
            auto& pool = graph_[u];
            std::sort(pool.begin(), pool.end());
            if (static_cast<int>(pool.size()) > kNumReverseEdges) {
                pool.resize(kNumReverseEdges);
            }
        }
    }

    const std::vector<std::vector<float>>& vectors_;
    std::vector<std::vector<Neighbor>> graph_;
    std::vector<std::vector<int>> layer0_;
};

std::vector<float> hnsw_assign_probas() {
    std::vector<float> assign_probas;
    const float level_mult = 1.0f / std::log(static_cast<float>(kHnswM));
    for (int level = 0;; ++level) {
        const float proba =
            std::exp(-level / level_mult) * (1.0f - std::exp(-1.0f / level_mult));
        if (proba < 1e-9f) {
            break;
        }
        assign_probas.push_back(proba);
    }
    return assign_probas;
}

int random_level(RandomGenerator& rng, const std::vector<float>& assign_probas) {
    float f = rng.rand_float();
    for (int level = 0; level < static_cast<int>(assign_probas.size()); ++level) {
        if (f < assign_probas[level]) {
            return level;
        }
        f -= assign_probas[level];
    }
    return static_cast<int>(assign_probas.size()) - 1;
}

std::vector<int> generate_levels() {
    RandomGenerator rng(kHnswLevelSeed);
    const std::vector<float> assign_probas = hnsw_assign_probas();
    std::vector<int> levels;
    levels.reserve(kN);
    for (int i = 0; i < kN; ++i) {
        levels.push_back(random_level(rng, assign_probas));
    }
    return levels;
}

std::map<int, std::vector<int>> upper_insert_order_by_level(const std::vector<int>& levels) {
    int max_level = 0;
    for (int level : levels) {
        max_level = std::max(max_level, level);
    }

    std::vector<std::vector<int>> buckets(max_level + 1);
    for (int i = 0; i < static_cast<int>(levels.size()); ++i) {
        buckets[levels[i]].push_back(i);
    }

    RandomGenerator rng(kShuffleSeed);
    std::map<int, std::vector<int>> order;
    for (int level = max_level; level > 0; --level) {
        auto& bucket = buckets[level];
        for (int j = 0; j < static_cast<int>(bucket.size()); ++j) {
            std::swap(bucket[j], bucket[j + rng.rand_int(static_cast<int>(bucket.size()) - j)]);
        }
        order[level] = bucket;
    }
    return order;
}

std::vector<std::vector<int>> top_s_layer0(const std::vector<std::vector<int>>& layer0) {
    std::vector<std::vector<int>> result;
    result.reserve(layer0.size());
    for (const auto& neighbors : layer0) {
        auto take = static_cast<size_t>(std::min<int>(kLayer0K, neighbors.size()));
        result.emplace_back(neighbors.begin(), neighbors.begin() + take);
    }
    return result;
}

std::vector<int> diagnostic_shrink_layer0_for_point(
        int u,
        const std::vector<int>& candidates,
        const std::vector<std::vector<float>>& vectors,
        int max_size) {
    std::priority_queue<NodeDistFarther> initial_list;

    for (int id : candidates) {
        if (id == u) {
            continue;
        }
        initial_list.emplace(l2_distance(vectors, u, id), id);
    }

    std::vector<NodeDistFarther> output;
    while (!initial_list.empty()) {
        NodeDistFarther v1 = initial_list.top();
        initial_list.pop();

        bool good = true;
        for (const NodeDistFarther& v2 : output) {
            const float dist_v1_v2 = l2_distance(vectors, v2.id, v1.id);
            if (dist_v1_v2 < v1.distance) {
                good = false;
                break;
            }
        }

        if (good) {
            output.push_back(v1);
            if (static_cast<int>(output.size()) >= max_size) {
                break;
            }
        }
    }

    std::vector<int> ids;
    ids.reserve(output.size());
    for (const NodeDistFarther& item : output) {
        ids.push_back(item.id);
    }
    return ids;
}

std::vector<std::vector<int>> diagnostic_injected_layer0(
        const std::vector<std::vector<int>>& layer0_top_s,
        const std::vector<std::vector<float>>& vectors) {
    std::vector<std::vector<int>> injected;
    injected.reserve(layer0_top_s.size());
    for (int u = 0; u < static_cast<int>(layer0_top_s.size()); ++u) {
        injected.push_back(diagnostic_shrink_layer0_for_point(
                u, layer0_top_s[u], vectors, kHnswM0));
    }
    return injected;
}

Layer0Stats compute_layer0_stats(const std::vector<std::vector<int>>& graph) {
    Layer0Stats stats;
    if (graph.empty()) {
        return stats;
    }

    stats.min_degree = static_cast<int>(graph[0].size());
    std::set<std::pair<int, int>> edges;

    for (int u = 0; u < static_cast<int>(graph.size()); ++u) {
        const int degree = static_cast<int>(graph[u].size());
        stats.total_edges += degree;
        stats.min_degree = std::min(stats.min_degree, degree);
        stats.max_degree = std::max(stats.max_degree, degree);
        stats.degree_histogram[degree] += 1;
        for (int v : graph[u]) {
            edges.emplace(u, v);
        }
    }

    stats.avg_degree = static_cast<double>(stats.total_edges) /
            static_cast<double>(graph.size());

    for (const auto& [u, v] : edges) {
        if (edges.find({v, u}) != edges.end()) {
            stats.reciprocal_edges += 1;
        }
    }
    stats.reciprocity_ratio = stats.total_edges == 0
            ? 0.0
            : static_cast<double>(stats.reciprocal_edges) /
                    static_cast<double>(stats.total_edges);

    std::vector<std::vector<int>> undirected(graph.size());
    for (const auto& [u, v] : edges) {
        if (v < 0 || v >= static_cast<int>(graph.size())) {
            continue;
        }
        undirected[u].push_back(v);
        undirected[v].push_back(u);
    }

    std::vector<bool> visited(graph.size(), false);
    std::vector<int> stack;
    for (int start = 0; start < static_cast<int>(graph.size()); ++start) {
        if (visited[start]) {
            continue;
        }
        stats.weak_connected_components += 1;
        int component_size = 0;
        stack.clear();
        stack.push_back(start);
        visited[start] = true;

        while (!stack.empty()) {
            const int u = stack.back();
            stack.pop_back();
            component_size += 1;

            for (int v : undirected[u]) {
                if (!visited[v]) {
                    visited[v] = true;
                    stack.push_back(v);
                }
            }
        }

        stats.largest_weak_component =
                std::max(stats.largest_weak_component, component_size);
    }

    return stats;
}

void print_vec(const std::vector<int>& values) {
    std::cout << "[";
    for (size_t i = 0; i < values.size(); ++i) {
        if (i != 0) {
            std::cout << ", ";
        }
        std::cout << values[i];
    }
    std::cout << "]";
}

void print_nested_vec(const std::vector<std::vector<int>>& values) {
    std::cout << "[\n";
    for (size_t i = 0; i < values.size(); ++i) {
        std::cout << "    ";
        print_vec(values[i]);
        if (i + 1 != values.size()) {
            std::cout << ",";
        }
        std::cout << "\n";
    }
    std::cout << "  ]";
}

void print_int_map(const std::map<int, int>& values) {
    std::cout << "{";
    for (auto it = values.begin(); it != values.end(); ++it) {
        if (it != values.begin()) {
            std::cout << ", ";
        }
        std::cout << "\"" << it->first << "\": " << it->second;
    }
    std::cout << "}";
}

void print_stats(const Layer0Stats& stats) {
    std::cout << "{\n";
    std::cout << "    \"total_edges\": " << stats.total_edges << ",\n";
    std::cout << "    \"min_degree\": " << stats.min_degree << ",\n";
    std::cout << "    \"max_degree\": " << stats.max_degree << ",\n";
    std::cout << "    \"avg_degree\": " << std::fixed << std::setprecision(6)
              << stats.avg_degree << ",\n";
    std::cout << "    \"degree_histogram\": ";
    print_int_map(stats.degree_histogram);
    std::cout << ",\n";
    std::cout << "    \"reciprocal_edges\": " << stats.reciprocal_edges << ",\n";
    std::cout << "    \"reciprocity_ratio\": " << std::fixed << std::setprecision(6)
              << stats.reciprocity_ratio << ",\n";
    std::cout << "    \"weak_connected_components\": "
              << stats.weak_connected_components << ",\n";
    std::cout << "    \"largest_weak_component\": "
              << stats.largest_weak_component << "\n";
    std::cout << "  }";
}

} // namespace

int main() {
    const auto vectors = generate_vectors();
    MirageReference mirage(vectors);
    mirage.build();

    const auto levels = generate_levels();
    const auto upper_order = upper_insert_order_by_level(levels);
    const auto layer0_top_s = top_s_layer0(mirage.layer0());
    const auto layer0_injected =
            diagnostic_injected_layer0(layer0_top_s, vectors);
    const auto layer0_injected_stats = compute_layer0_stats(layer0_injected);

    std::cout << "{\n";
    std::cout << "  \"version\": 1,\n";
    std::cout << "  \"source\": \"tools/mirage_golden/dump_mirage_golden.cpp mirrors local C++ MIRAGE.cpp; layer0_injected is diagnostic self-contained shrink output\",\n";
    std::cout << "  \"metric\": \"l2\",\n";
    std::cout << "  \"vector_generator\": \"integer-affine-v1\",\n";
    std::cout << "  \"layer0_injected_source\": \"diagnostic_self_contained_shrink; regenerate with dump_mirage_authoritative.cpp for real C++ hierarchy.hnsw.neighbors\",\n";
    std::cout << "  \"n\": " << kN << ",\n";
    std::cout << "  \"dim\": " << kDim << ",\n";
    std::cout << "  \"params\": {\n";
    std::cout << "    \"s\": " << kS << ",\n";
    std::cout << "    \"r\": " << kR << ",\n";
    std::cout << "    \"iter\": " << kIter << ",\n";
    std::cout << "    \"num_reverse_edges\": " << kNumReverseEdges << ",\n";
    std::cout << "    \"mirage_seed\": " << kMirageSeed << ",\n";
    std::cout << "    \"hnsw_m\": " << kHnswM << ",\n";
    std::cout << "    \"hnsw_m0\": " << kHnswM0 << ",\n";
    std::cout << "    \"layer0_k\": " << kLayer0K << ",\n";
    std::cout << "    \"hnsw_level_seed\": " << kHnswLevelSeed << ",\n";
    std::cout << "    \"shuffle_seed\": " << kShuffleSeed << ",\n";
    std::cout << "    \"threads\": 1\n";
    std::cout << "  },\n";
    std::cout << "  \"levels_zero_based\": ";
    print_vec(levels);
    std::cout << ",\n";
    std::cout << "  \"upper_insert_order_by_level\": {\n";
    for (auto it = upper_order.begin(); it != upper_order.end(); ++it) {
        std::cout << "    \"" << it->first << "\": ";
        print_vec(it->second);
        if (std::next(it) != upper_order.end()) {
            std::cout << ",";
        }
        std::cout << "\n";
    }
    std::cout << "  },\n";
    std::cout << "  \"layer0\": ";
    print_nested_vec(mirage.layer0());
    std::cout << ",\n";
    std::cout << "  \"layer0_top_s\": ";
    print_nested_vec(layer0_top_s);
    std::cout << ",\n";
    std::cout << "  \"layer0_injected\": ";
    print_nested_vec(layer0_injected);
    std::cout << ",\n";
    std::cout << "  \"layer0_injected_stats\": ";
    print_stats(layer0_injected_stats);
    std::cout << "\n";
    std::cout << "}\n";
    return 0;
}
